Remove testing workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,11 +11,45 @@ on:
 # can split them up later.
 
 jobs:
-  shared-lib:
-    uses: ./.github/workflows/feature-shared-lib.yml
-    secrets: inherit
+  tag:
+    outputs:
+      image-tag: ${{ steps.extract-tag.outputs.image-tag }}
+    steps:
+    - name: init
+      id: extract-tag
+      run: |
+        
+        # In case a workflow, using the self-hosted runner, has failed and
+        # the kind cluster is still running.
+        kind delete clusters kind
+        
+        TAG=$(echo ${{ github.event.head_commit.message }} | awk '{ print $2 }')
+        
+        echo "Head commit message: ${{ github.event.head_commit.message }}"
+        echo "Extracted tag: $TAG."
+        
+        # Validate tag format
+        # Format of commit message: RELEASE <tag> - <message>
+        # Format of tag (change numbers or dev, but leave everything else): 
+        #   v0.0.5-dev
+        #   v0.0.5
+        if [[ $TAG =~ ^v[0-9]+.[0-9]+.([0-9]+-[a-z]+|[0-9]+)$ ]]
+        then
+          echo "Valid format, proceed with test."
+        else
+          echo "Tag format is invalid."
+          exit 1
+        fi
+
+        echo "release-tag=$TAG" >> $GITHUB_OUTPUT
+  build-all:
+    needs: tag
+    runs-on: ubuntu-latest
+    uses: ./.github/workflows/develop.yml
+    with:
+      image-tag: ${{ needs.tag.outputs.image-tag }}
   release:
-    needs: shared-lib
+    needs: [tag, build-all]
     runs-on: self-hosted
     environment: docker-publish-account
     # Enviroment that contains the required secrets.
@@ -23,103 +57,6 @@ jobs:
       - name: Check out repository code
         uses: actions/checkout@v3
         # Is required to call actions.
-
-      - name: init
-        run: |
-
-          # In case a workflow, using the self-hosted runner, has failed and
-          # the kind cluster is still running.
-          kind delete clusters kind
-
-          TAG=$(echo ${{ github.event.head_commit.message }} | awk '{ print $2 }')
-
-          echo "Head commit message: ${{ github.event.head_commit.message }}"
-          echo "Extracted tag: $TAG."
-
-          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
-
-          # Validate tag format
-          # Format of commit message: RELEASE <tag> - <message>
-          # Format of tag (change numbers or dev, but leave everything else): 
-          #   v0.0.5-dev
-          #   v0.0.5
-          if [[ $TAG =~ ^v[0-9]+.[0-9]+.([0-9]+-[a-z]+|[0-9]+)$ ]]
-          then
-            echo "Valid format, proceed with test."
-          else
-            echo "Tag format is invalid."
-            exit 1
-          fi
-
-      - name: feature-grafana
-        id: action-grafana
-        uses: ./.github/actions/grafana
-        with:
-          dir-location: 'grafana'
-
-      - name: feature-keycloak-ui
-        id: action-feature-keycloak-ui
-        uses: ./.github/actions/keycloak-ui
-        with:
-          dir-location: 'keycloak-ui'
-
-      - name: feature-ui
-        id: action-feature-ui
-        uses: ./.github/actions/ui
-        with:
-          dir-location: 'ui'
-
-      - name: feature-core
-        id: action-feature-core
-        uses: ./.github/actions/core
-        with:
-          dir-location: 'platform'
-
-      - name: feature-metrics-processor
-        id: action-feature-metrics-processor
-        uses: ./.github/actions/metrics-processor
-
-      - name: feature-rest-server
-        id: action-rest-server
-        uses: ./.github/actions/rest-server
-        with:
-          dir-location: 'rest-server'
-
-      - name: feature-inventory
-        id: action-inventory
-        uses: ./.github/actions/inventory
-        with:
-          dir-location: 'inventory'
-      
-      - name: feature-notifications
-        id: action-notifications
-        uses: ./.github/actions/notifications
-        with:
-          dir-location: 'notifications'
-      
-      - name: feature-operator
-        id: action-feature-operator
-        uses: ./.github/actions/operator
-        with:
-          dir-location: 'operator'
-
-      - name: feature-minion
-        id: action-minion
-        uses: ./.github/actions/minion
-        with:
-          dir-location: 'minion'
-
-      - name: feature-minion-gateway
-        id: action-minion-gateway
-        uses: ./.github/actions/minion-gateway
-        with:
-          dir-location: 'minion-gateway'
-
-      - name: external-it
-        id: action-external-it
-        uses: ./.github/actions/external-it
-        with:
-          dir-location: 'external-it'
       
       - name: dockerhub-login
         run: |
@@ -142,11 +79,11 @@ jobs:
           cd minion/
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-minion:local opennms/horizon-stream-minion:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-minion:local opennms/horizon-stream-minion:latest
+          docker tag opennms/horizon-stream-minion:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-minion:latest
 
-          docker push opennms/horizon-stream-minion:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-minion:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-minion:latest
+
 
       - name: publish-image-minion-gateway
         run: |
@@ -158,10 +95,9 @@ jobs:
           cd minion-gateway/
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-minion-gateway:local opennms/horizon-stream-minion-gateway:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-minion-gateway:local opennms/horizon-stream-minion-gateway:latest
+          docker tag opennms/horizon-stream-minion-gateway:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-minion-gateway:latest
 
-          docker push opennms/horizon-stream-minion-gateway:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-minion-gateway:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-minion-gateway:latest
 
       - name: publish-image-core
@@ -174,10 +110,9 @@ jobs:
           cd platform/
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-core:local opennms/horizon-stream-core:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-core:local opennms/horizon-stream-core:latest
+          docker tag opennms/horizon-stream-core:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-core:latest
 
-          docker push opennms/horizon-stream-core:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-core:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-core:latest
       
       - name: publish-image-ui
@@ -187,10 +122,9 @@ jobs:
           echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-ui:local opennms/horizon-stream-ui:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-ui:local opennms/horizon-stream-ui:latest
+          docker tag opennms/horizon-stream-ui:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-ui:latest
 
-          docker push opennms/horizon-stream-ui:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-ui:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-ui:latest
 
       - name: publish-image-keycloak-ui
@@ -200,10 +134,9 @@ jobs:
           echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-keycloak:local opennms/horizon-stream-keycloak:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-keycloak:local opennms/horizon-stream-keycloak:latest
+          docker tag opennms/horizon-stream-keycloak:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-keycloak:latest
 
-          docker push opennms/horizon-stream-keycloak:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-keycloak:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-keycloak:latest
 
       - name: publish-image-grafana
@@ -213,10 +146,9 @@ jobs:
           echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-grafana:local opennms/horizon-stream-grafana:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-grafana:local opennms/horizon-stream-grafana:latest
+          docker tag opennms/horizon-stream-grafana:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-grafana:latest
 
-          docker push opennms/horizon-stream-grafana:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-grafana:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-grafana:latest
 
       - name: publish-image-rest-server
@@ -229,10 +161,9 @@ jobs:
           docker images
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-rest-server:local opennms/horizon-stream-rest-server:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-rest-server:local opennms/horizon-stream-rest-server:latest
+          docker tag opennms/horizon-stream-rest-server:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-rest-server:latest
 
-          docker push opennms/horizon-stream-rest-server:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-rest-server:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-rest-server:latest
 
       - name: publish-image-inventory
@@ -245,10 +176,9 @@ jobs:
           docker images
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-inventory:local opennms/horizon-stream-inventory:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-inventory:local opennms/horizon-stream-inventory:latest
+          docker tag opennms/horizon-stream-inventory:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-inventory:latest
 
-          docker push opennms/horizon-stream-inventory:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-inventory:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-inventory:latest
       
       - name: publish-image-metrics-processor
@@ -261,10 +191,9 @@ jobs:
           docker images
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-metrics-processor:local opennms/horizon-stream-metrics-processor:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-metrics-processor:local opennms/horizon-stream-metrics-processor:latest
+          docker tag opennms/horizon-stream-metrics-processor:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-metrics-processor:latest
 
-          docker push opennms/horizon-stream-metrics-processor:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-metrics-processor:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-metrics-processor:latest
       
       - name: publish-image-notifications
@@ -277,23 +206,20 @@ jobs:
           docker images
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/horizon-stream-notification:local opennms/horizon-stream-notification:${{ env.RELEASE_TAG }}
-          docker tag opennms/horizon-stream-notification:local opennms/horizon-stream-notification:latest
+          docker tag opennms/horizon-stream-notification:${{ needs.tag.outputs.image-tag }} opennms/horizon-stream-notification:latest
 
-          docker push opennms/horizon-stream-notification:${{ env.RELEASE_TAG }}
+          docker push opennms/horizon-stream-notification:${{ needs.tag.outputs.image-tag }}
           docker push opennms/horizon-stream-notification:latest
       
       - name: publish-image-operator
         run: |
-
           # Login to dockerhub.
           echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
 
           # Tag and save the image as a file to be published. Both release version and latest.
-          docker tag opennms/operator:local-build opennms/operator:${{ env.RELEASE_TAG }}
-          docker tag opennms/operator:local-build opennms/operator:latest
+          docker tag opennms/operator:${{ needs.tag.outputs.image-tag }} opennms/operator:latest
 
-          docker push opennms/operator:${{ env.RELEASE_TAG }}
+          docker push opennms/operator:${{ needs.tag.outputs.image-tag }}
           docker push opennms/operator:latest
 
       #- name: tag-release-branch
@@ -302,7 +228,7 @@ jobs:
       #    # The following checkouts the release branch and merges develop into
       #    # it and then tags release.
       #    git fetch
-      #    git tag ${{ env.RELEASE_TAG }}
-      #    git push origin ${{ env.RELEASE_TAG }}
+      #    git tag ${{ needs.tag.outputs.image-tag }}
+      #    git push origin ${{ needs.tag.outputs.image-tag }}
 
 
